package objects
{
	import flash.utils.*;
	import flash.geom.*;
	import mx.collections.*;
	import mx.containers.*;
	import mx.core.*;
	
	// WARNING: This file is autogenerated by template
	// If you wish to modify this file, modify its template and then generate a new version
	public class WordDefinitions
	{
		protected static var instance:WordDefinitions = null;
		
		public var Words:Array = new Array();
		public var WordsByLetter:Array = new Array();
		protected var canvas:Canvas = null;
		
		static public function get Instance():WordDefinitions
		{
			if ( instance == null )
				instance = new WordDefinitions();
			return instance;
		}
		
		public function WordDefinitions()
		{
			
		}

		// Images
		public static var AladdinImages:Array = new Array();
		[Embed(source="../../media/words/aladdin_1.jpg")]
		public static var WordImageAladdin1:Class;
		AladdinImages[AladdinImages.length] = new WordImageAladdin1();

		[Embed(source="../../media/words/aladdin_2.jpg")]
		public static var WordImageAladdin2:Class;
		AladdinImages[AladdinImages.length] = new WordImageAladdin2();

		public static var ArielImages:Array = new Array();
		[Embed(source="../../media/words/ariel_1.jpg")]
		public static var WordImageAriel1:Class;
		ArielImages[ArielImages.length] = new WordImageAriel1();

		[Embed(source="../../media/words/ariel_10.jpg")]
		public static var WordImageAriel10:Class;
		ArielImages[ArielImages.length] = new WordImageAriel10();

		[Embed(source="../../media/words/ariel_11.gif")]
		public static var WordImageAriel11:Class;
		ArielImages[ArielImages.length] = new WordImageAriel11();

		[Embed(source="../../media/words/ariel_2.jpg")]
		public static var WordImageAriel2:Class;
		ArielImages[ArielImages.length] = new WordImageAriel2();

		[Embed(source="../../media/words/ariel_3.jpg")]
		public static var WordImageAriel3:Class;
		ArielImages[ArielImages.length] = new WordImageAriel3();

		[Embed(source="../../media/words/ariel_4.gif")]
		public static var WordImageAriel4:Class;
		ArielImages[ArielImages.length] = new WordImageAriel4();

		[Embed(source="../../media/words/ariel_5.jpg")]
		public static var WordImageAriel5:Class;
		ArielImages[ArielImages.length] = new WordImageAriel5();

		[Embed(source="../../media/words/ariel_6.jpg")]
		public static var WordImageAriel6:Class;
		ArielImages[ArielImages.length] = new WordImageAriel6();

		[Embed(source="../../media/words/ariel_7.jpg")]
		public static var WordImageAriel7:Class;
		ArielImages[ArielImages.length] = new WordImageAriel7();

		[Embed(source="../../media/words/ariel_8.gif")]
		public static var WordImageAriel8:Class;
		ArielImages[ArielImages.length] = new WordImageAriel8();

		[Embed(source="../../media/words/ariel_9.jpg")]
		public static var WordImageAriel9:Class;
		ArielImages[ArielImages.length] = new WordImageAriel9();

		public static var BambiImages:Array = new Array();
		[Embed(source="../../media/words/bambi_1.jpg")]
		public static var WordImageBambi1:Class;
		BambiImages[BambiImages.length] = new WordImageBambi1();

		public static var BeastImages:Array = new Array();
		[Embed(source="../../media/words/beast_1.jpg")]
		public static var WordImageBeast1:Class;
		BeastImages[BeastImages.length] = new WordImageBeast1();

		[Embed(source="../../media/words/beast_2.jpg")]
		public static var WordImageBeast2:Class;
		BeastImages[BeastImages.length] = new WordImageBeast2();

		[Embed(source="../../media/words/beast_3.jpg")]
		public static var WordImageBeast3:Class;
		BeastImages[BeastImages.length] = new WordImageBeast3();

		[Embed(source="../../media/words/beast_4.gif")]
		public static var WordImageBeast4:Class;
		BeastImages[BeastImages.length] = new WordImageBeast4();

		[Embed(source="../../media/words/beast_5.gif")]
		public static var WordImageBeast5:Class;
		BeastImages[BeastImages.length] = new WordImageBeast5();

		[Embed(source="../../media/words/beast_6.gif")]
		public static var WordImageBeast6:Class;
		BeastImages[BeastImages.length] = new WordImageBeast6();

		[Embed(source="../../media/words/beast_7.gif")]
		public static var WordImageBeast7:Class;
		BeastImages[BeastImages.length] = new WordImageBeast7();

		[Embed(source="../../media/words/beast_8.jpg")]
		public static var WordImageBeast8:Class;
		BeastImages[BeastImages.length] = new WordImageBeast8();

		public static var BelleImages:Array = new Array();
		[Embed(source="../../media/words/belle_1.jpg")]
		public static var WordImageBelle1:Class;
		BelleImages[BelleImages.length] = new WordImageBelle1();

		[Embed(source="../../media/words/belle_2.jpg")]
		public static var WordImageBelle2:Class;
		BelleImages[BelleImages.length] = new WordImageBelle2();

		[Embed(source="../../media/words/belle_3.gif")]
		public static var WordImageBelle3:Class;
		BelleImages[BelleImages.length] = new WordImageBelle3();

		[Embed(source="../../media/words/belle_4.jpg")]
		public static var WordImageBelle4:Class;
		BelleImages[BelleImages.length] = new WordImageBelle4();

		public static var BlossomImages:Array = new Array();
		[Embed(source="../../media/words/blossom_1.jpg")]
		public static var WordImageBlossom1:Class;
		BlossomImages[BlossomImages.length] = new WordImageBlossom1();

		[Embed(source="../../media/words/blossom_2.jpg")]
		public static var WordImageBlossom2:Class;
		BlossomImages[BlossomImages.length] = new WordImageBlossom2();

		[Embed(source="../../media/words/blossom_3.gif")]
		public static var WordImageBlossom3:Class;
		BlossomImages[BlossomImages.length] = new WordImageBlossom3();

		public static var BubblesImages:Array = new Array();
		[Embed(source="../../media/words/bubbles_1.gif")]
		public static var WordImageBubbles1:Class;
		BubblesImages[BubblesImages.length] = new WordImageBubbles1();

		[Embed(source="../../media/words/bubbles_2.gif")]
		public static var WordImageBubbles2:Class;
		BubblesImages[BubblesImages.length] = new WordImageBubbles2();

		[Embed(source="../../media/words/bubbles_3.jpg")]
		public static var WordImageBubbles3:Class;
		BubblesImages[BubblesImages.length] = new WordImageBubbles3();

		public static var ButtercupImages:Array = new Array();
		[Embed(source="../../media/words/buttercup_1.jpg")]
		public static var WordImageButtercup1:Class;
		ButtercupImages[ButtercupImages.length] = new WordImageButtercup1();

		[Embed(source="../../media/words/buttercup_2.jpg")]
		public static var WordImageButtercup2:Class;
		ButtercupImages[ButtercupImages.length] = new WordImageButtercup2();

		public static var CatImages:Array = new Array();
		[Embed(source="../../media/words/cat_1.jpg")]
		public static var WordImageCat1:Class;
		CatImages[CatImages.length] = new WordImageCat1();

		public static var ChipImages:Array = new Array();
		[Embed(source="../../media/words/chip_1.gif")]
		public static var WordImageChip1:Class;
		ChipImages[ChipImages.length] = new WordImageChip1();

		[Embed(source="../../media/words/chip_2.jpg")]
		public static var WordImageChip2:Class;
		ChipImages[ChipImages.length] = new WordImageChip2();

		public static var CinderellaImages:Array = new Array();
		[Embed(source="../../media/words/cinderella_1.jpg")]
		public static var WordImageCinderella1:Class;
		CinderellaImages[CinderellaImages.length] = new WordImageCinderella1();

		[Embed(source="../../media/words/cinderella_2.jpg")]
		public static var WordImageCinderella2:Class;
		CinderellaImages[CinderellaImages.length] = new WordImageCinderella2();

		public static var CogsworthImages:Array = new Array();
		[Embed(source="../../media/words/cogsworth_1.gif")]
		public static var WordImageCogsworth1:Class;
		CogsworthImages[CogsworthImages.length] = new WordImageCogsworth1();

		public static var DaisyImages:Array = new Array();
		[Embed(source="../../media/words/daisy_1.jpg")]
		public static var WordImageDaisy1:Class;
		DaisyImages[DaisyImages.length] = new WordImageDaisy1();

		public static var DogImages:Array = new Array();
		[Embed(source="../../media/words/dog_1.jpg")]
		public static var WordImageDog1:Class;
		DogImages[DogImages.length] = new WordImageDog1();

		public static var DonaldImages:Array = new Array();
		[Embed(source="../../media/words/donald_1.jpg")]
		public static var WordImageDonald1:Class;
		DonaldImages[DonaldImages.length] = new WordImageDonald1();

		public static var DonkeyImages:Array = new Array();
		[Embed(source="../../media/words/donkey_1.jpg")]
		public static var WordImageDonkey1:Class;
		DonkeyImages[DonkeyImages.length] = new WordImageDonkey1();

		public static var DopeyImages:Array = new Array();
		[Embed(source="../../media/words/dopey_1.jpg")]
		public static var WordImageDopey1:Class;
		DopeyImages[DopeyImages.length] = new WordImageDopey1();

		public static var DorothyImages:Array = new Array();
		[Embed(source="../../media/words/dorothy_1.jpg")]
		public static var WordImageDorothy1:Class;
		DorothyImages[DorothyImages.length] = new WordImageDorothy1();

		public static var DragonImages:Array = new Array();
		[Embed(source="../../media/words/dragon_1.gif")]
		public static var WordImageDragon1:Class;
		DragonImages[DragonImages.length] = new WordImageDragon1();

		[Embed(source="../../media/words/dragon_2.jpg")]
		public static var WordImageDragon2:Class;
		DragonImages[DragonImages.length] = new WordImageDragon2();

		public static var DumboImages:Array = new Array();
		[Embed(source="../../media/words/dumbo_1.jpg")]
		public static var WordImageDumbo1:Class;
		DumboImages[DumboImages.length] = new WordImageDumbo1();

		public static var EeyoreImages:Array = new Array();
		[Embed(source="../../media/words/eeyore_1.jpg")]
		public static var WordImageEeyore1:Class;
		EeyoreImages[EeyoreImages.length] = new WordImageEeyore1();

		public static var EggImages:Array = new Array();
		[Embed(source="../../media/words/egg_1.jpg")]
		public static var WordImageEgg1:Class;
		EggImages[EggImages.length] = new WordImageEgg1();

		public static var EricImages:Array = new Array();
		[Embed(source="../../media/words/eric_1.jpg")]
		public static var WordImageEric1:Class;
		EricImages[EricImages.length] = new WordImageEric1();

		[Embed(source="../../media/words/eric_2.jpg")]
		public static var WordImageEric2:Class;
		EricImages[EricImages.length] = new WordImageEric2();

		public static var FairyImages:Array = new Array();
		[Embed(source="../../media/words/fairy_1.gif")]
		public static var WordImageFairy1:Class;
		FairyImages[FairyImages.length] = new WordImageFairy1();

		public static var FionaImages:Array = new Array();
		[Embed(source="../../media/words/fiona_1.jpg")]
		public static var WordImageFiona1:Class;
		FionaImages[FionaImages.length] = new WordImageFiona1();

		[Embed(source="../../media/words/fiona_2.jpg")]
		public static var WordImageFiona2:Class;
		FionaImages[FionaImages.length] = new WordImageFiona2();

		public static var FlounderImages:Array = new Array();
		[Embed(source="../../media/words/flounder_1.jpg")]
		public static var WordImageFlounder1:Class;
		FlounderImages[FlounderImages.length] = new WordImageFlounder1();

		[Embed(source="../../media/words/flounder_10.gif")]
		public static var WordImageFlounder10:Class;
		FlounderImages[FlounderImages.length] = new WordImageFlounder10();

		[Embed(source="../../media/words/flounder_11.jpg")]
		public static var WordImageFlounder11:Class;
		FlounderImages[FlounderImages.length] = new WordImageFlounder11();

		[Embed(source="../../media/words/flounder_12.jpg")]
		public static var WordImageFlounder12:Class;
		FlounderImages[FlounderImages.length] = new WordImageFlounder12();

		[Embed(source="../../media/words/flounder_2.jpg")]
		public static var WordImageFlounder2:Class;
		FlounderImages[FlounderImages.length] = new WordImageFlounder2();

		[Embed(source="../../media/words/flounder_3.jpg")]
		public static var WordImageFlounder3:Class;
		FlounderImages[FlounderImages.length] = new WordImageFlounder3();

		[Embed(source="../../media/words/flounder_4.jpg")]
		public static var WordImageFlounder4:Class;
		FlounderImages[FlounderImages.length] = new WordImageFlounder4();

		[Embed(source="../../media/words/flounder_5.jpg")]
		public static var WordImageFlounder5:Class;
		FlounderImages[FlounderImages.length] = new WordImageFlounder5();

		[Embed(source="../../media/words/flounder_6.jpg")]
		public static var WordImageFlounder6:Class;
		FlounderImages[FlounderImages.length] = new WordImageFlounder6();

		[Embed(source="../../media/words/flounder_7.jpg")]
		public static var WordImageFlounder7:Class;
		FlounderImages[FlounderImages.length] = new WordImageFlounder7();

		[Embed(source="../../media/words/flounder_8.jpg")]
		public static var WordImageFlounder8:Class;
		FlounderImages[FlounderImages.length] = new WordImageFlounder8();

		[Embed(source="../../media/words/flounder_9.jpg")]
		public static var WordImageFlounder9:Class;
		FlounderImages[FlounderImages.length] = new WordImageFlounder9();

		public static var FlynnRiderImages:Array = new Array();
		[Embed(source="../../media/words/flynn-rider_1.jpg")]
		public static var WordImageFlynnRider1:Class;
		FlynnRiderImages[FlynnRiderImages.length] = new WordImageFlynnRider1();

		[Embed(source="../../media/words/flynn-rider_2.jpg")]
		public static var WordImageFlynnRider2:Class;
		FlynnRiderImages[FlynnRiderImages.length] = new WordImageFlynnRider2();

		public static var GastonImages:Array = new Array();
		[Embed(source="../../media/words/gaston_1.gif")]
		public static var WordImageGaston1:Class;
		GastonImages[GastonImages.length] = new WordImageGaston1();

		public static var GenieImages:Array = new Array();
		[Embed(source="../../media/words/genie_1.gif")]
		public static var WordImageGenie1:Class;
		GenieImages[GenieImages.length] = new WordImageGenie1();

		[Embed(source="../../media/words/genie_2.jpg")]
		public static var WordImageGenie2:Class;
		GenieImages[GenieImages.length] = new WordImageGenie2();

		public static var GingerbreadManImages:Array = new Array();
		[Embed(source="../../media/words/gingerbread-man_1.jpg")]
		public static var WordImageGingerbreadMan1:Class;
		GingerbreadManImages[GingerbreadManImages.length] = new WordImageGingerbreadMan1();

		public static var GoofyImages:Array = new Array();
		[Embed(source="../../media/words/goofy_1.gif")]
		public static var WordImageGoofy1:Class;
		GoofyImages[GoofyImages.length] = new WordImageGoofy1();

		public static var GusGusImages:Array = new Array();
		[Embed(source="../../media/words/gus-gus_1.gif")]
		public static var WordImageGusGus1:Class;
		GusGusImages[GusGusImages.length] = new WordImageGusGus1();

		public static var HamsterImages:Array = new Array();
		[Embed(source="../../media/words/hamster_1.jpg")]
		public static var WordImageHamster1:Class;
		HamsterImages[HamsterImages.length] = new WordImageHamster1();

		public static var HannahMontanaImages:Array = new Array();
		[Embed(source="../../media/words/hannah-montana_1.jpg")]
		public static var WordImageHannahMontana1:Class;
		HannahMontanaImages[HannahMontanaImages.length] = new WordImageHannahMontana1();

		[Embed(source="../../media/words/hannah-montana_2.jpg")]
		public static var WordImageHannahMontana2:Class;
		HannahMontanaImages[HannahMontanaImages.length] = new WordImageHannahMontana2();

		public static var HippoImages:Array = new Array();
		[Embed(source="../../media/words/hippo_1.jpg")]
		public static var WordImageHippo1:Class;
		HippoImages[HippoImages.length] = new WordImageHippo1();

		public static var IagoImages:Array = new Array();
		[Embed(source="../../media/words/iago_1.gif")]
		public static var WordImageIago1:Class;
		IagoImages[IagoImages.length] = new WordImageIago1();

		public static var IceCreamImages:Array = new Array();
		[Embed(source="../../media/words/ice-cream_1.jpg")]
		public static var WordImageIceCream1:Class;
		IceCreamImages[IceCreamImages.length] = new WordImageIceCream1();

		public static var JaqImages:Array = new Array();
		[Embed(source="../../media/words/jaq_1.gif")]
		public static var WordImageJaq1:Class;
		JaqImages[JaqImages.length] = new WordImageJaq1();

		public static var JasmineImages:Array = new Array();
		[Embed(source="../../media/words/jasmine_1.jpg")]
		public static var WordImageJasmine1:Class;
		JasmineImages[JasmineImages.length] = new WordImageJasmine1();

		public static var JessieImages:Array = new Array();
		[Embed(source="../../media/words/jessie_1.jpg")]
		public static var WordImageJessie1:Class;
		JessieImages[JessieImages.length] = new WordImageJessie1();

		public static var JiminyCricketImages:Array = new Array();
		[Embed(source="../../media/words/jiminy-cricket_1.jpg")]
		public static var WordImageJiminyCricket1:Class;
		JiminyCricketImages[JiminyCricketImages.length] = new WordImageJiminyCricket1();

		[Embed(source="../../media/words/jiminy-cricket_2.gif")]
		public static var WordImageJiminyCricket2:Class;
		JiminyCricketImages[JiminyCricketImages.length] = new WordImageJiminyCricket2();

		public static var KingTritonImages:Array = new Array();
		[Embed(source="../../media/words/king-triton_1.jpg")]
		public static var WordImageKingTriton1:Class;
		KingTritonImages[KingTritonImages.length] = new WordImageKingTriton1();

		[Embed(source="../../media/words/king-triton_2.jpg")]
		public static var WordImageKingTriton2:Class;
		KingTritonImages[KingTritonImages.length] = new WordImageKingTriton2();

		[Embed(source="../../media/words/king-triton_3.jpg")]
		public static var WordImageKingTriton3:Class;
		KingTritonImages[KingTritonImages.length] = new WordImageKingTriton3();

		[Embed(source="../../media/words/king-triton_4.jpg")]
		public static var WordImageKingTriton4:Class;
		KingTritonImages[KingTritonImages.length] = new WordImageKingTriton4();

		[Embed(source="../../media/words/king-triton_5.gif")]
		public static var WordImageKingTriton5:Class;
		KingTritonImages[KingTritonImages.length] = new WordImageKingTriton5();

		[Embed(source="../../media/words/king-triton_6.jpg")]
		public static var WordImageKingTriton6:Class;
		KingTritonImages[KingTritonImages.length] = new WordImageKingTriton6();

		[Embed(source="../../media/words/king-triton_7.jpg")]
		public static var WordImageKingTriton7:Class;
		KingTritonImages[KingTritonImages.length] = new WordImageKingTriton7();

		[Embed(source="../../media/words/king-triton_8.gif")]
		public static var WordImageKingTriton8:Class;
		KingTritonImages[KingTritonImages.length] = new WordImageKingTriton8();

		[Embed(source="../../media/words/king-triton_9.jpg")]
		public static var WordImageKingTriton9:Class;
		KingTritonImages[KingTritonImages.length] = new WordImageKingTriton9();

		public static var KittenImages:Array = new Array();
		[Embed(source="../../media/words/kitten_1.jpg")]
		public static var WordImageKitten1:Class;
		KittenImages[KittenImages.length] = new WordImageKitten1();

		[Embed(source="../../media/words/kitten_2.jpg")]
		public static var WordImageKitten2:Class;
		KittenImages[KittenImages.length] = new WordImageKitten2();

		public static var LionImages:Array = new Array();
		[Embed(source="../../media/words/lion_1.jpg")]
		public static var WordImageLion1:Class;
		LionImages[LionImages.length] = new WordImageLion1();

		public static var LouisImages:Array = new Array();
		[Embed(source="../../media/words/louis_1.jpg")]
		public static var WordImageLouis1:Class;
		LouisImages[LouisImages.length] = new WordImageLouis1();

		public static var LumiereImages:Array = new Array();
		[Embed(source="../../media/words/lumiere_1.jpg")]
		public static var WordImageLumiere1:Class;
		LumiereImages[LumiereImages.length] = new WordImageLumiere1();

		[Embed(source="../../media/words/lumiere_2.gif")]
		public static var WordImageLumiere2:Class;
		LumiereImages[LumiereImages.length] = new WordImageLumiere2();

		public static var MaleficentImages:Array = new Array();
		[Embed(source="../../media/words/maleficent_1.jpg")]
		public static var WordImageMaleficent1:Class;
		MaleficentImages[MaleficentImages.length] = new WordImageMaleficent1();

		public static var MickeyImages:Array = new Array();
		[Embed(source="../../media/words/mickey_1.jpeg")]
		public static var WordImageMickey1:Class;
		MickeyImages[MickeyImages.length] = new WordImageMickey1();

		public static var MinnieImages:Array = new Array();
		[Embed(source="../../media/words/minnie_1.jpg")]
		public static var WordImageMinnie1:Class;
		MinnieImages[MinnieImages.length] = new WordImageMinnie1();

		public static var MojoJojoImages:Array = new Array();
		[Embed(source="../../media/words/mojo-jojo_1.jpg")]
		public static var WordImageMojoJojo1:Class;
		MojoJojoImages[MojoJojoImages.length] = new WordImageMojoJojo1();

		public static var NaveenImages:Array = new Array();
		[Embed(source="../../media/words/naveen_1.jpg")]
		public static var WordImageNaveen1:Class;
		NaveenImages[NaveenImages.length] = new WordImageNaveen1();

		public static var OwlImages:Array = new Array();
		[Embed(source="../../media/words/owl_1.jpg")]
		public static var WordImageOwl1:Class;
		OwlImages[OwlImages.length] = new WordImageOwl1();

		public static var PascalImages:Array = new Array();
		[Embed(source="../../media/words/pascal_1.jpg")]
		public static var WordImagePascal1:Class;
		PascalImages[PascalImages.length] = new WordImagePascal1();

		[Embed(source="../../media/words/pascal_2.jpg")]
		public static var WordImagePascal2:Class;
		PascalImages[PascalImages.length] = new WordImagePascal2();

		[Embed(source="../../media/words/pascal_3.jpg")]
		public static var WordImagePascal3:Class;
		PascalImages[PascalImages.length] = new WordImagePascal3();

		public static var PinocchioImages:Array = new Array();
		[Embed(source="../../media/words/pinocchio_1.jpg")]
		public static var WordImagePinocchio1:Class;
		PinocchioImages[PinocchioImages.length] = new WordImagePinocchio1();

		public static var PlutoImages:Array = new Array();
		[Embed(source="../../media/words/pluto_1.jpg")]
		public static var WordImagePluto1:Class;
		PlutoImages[PlutoImages.length] = new WordImagePluto1();

		public static var PowerpuffGirlsImages:Array = new Array();
		[Embed(source="../../media/words/powerpuff-girls_1.jpg")]
		public static var WordImagePowerpuffGirls1:Class;
		PowerpuffGirlsImages[PowerpuffGirlsImages.length] = new WordImagePowerpuffGirls1();

		public static var PrinceImages:Array = new Array();
		[Embed(source="../../media/words/prince_1.gif")]
		public static var WordImagePrince1:Class;
		PrinceImages[PrinceImages.length] = new WordImagePrince1();

		[Embed(source="../../media/words/prince_2.jpg")]
		public static var WordImagePrince2:Class;
		PrinceImages[PrinceImages.length] = new WordImagePrince2();

		[Embed(source="../../media/words/prince_3.jpg")]
		public static var WordImagePrince3:Class;
		PrinceImages[PrinceImages.length] = new WordImagePrince3();

		public static var PussInBootsImages:Array = new Array();
		[Embed(source="../../media/words/puss-in-boots_1.jpg")]
		public static var WordImagePussInBoots1:Class;
		PussInBootsImages[PussInBootsImages.length] = new WordImagePussInBoots1();

		[Embed(source="../../media/words/puss-in-boots_2.jpg")]
		public static var WordImagePussInBoots2:Class;
		PussInBootsImages[PussInBootsImages.length] = new WordImagePussInBoots2();

		public static var QueenImages:Array = new Array();
		[Embed(source="../../media/words/queen_1.jpg")]
		public static var WordImageQueen1:Class;
		QueenImages[QueenImages.length] = new WordImageQueen1();

		[Embed(source="../../media/words/queen_2.jpg")]
		public static var WordImageQueen2:Class;
		QueenImages[QueenImages.length] = new WordImageQueen2();

		public static var RajahImages:Array = new Array();
		[Embed(source="../../media/words/rajah_1.gif")]
		public static var WordImageRajah1:Class;
		RajahImages[RajahImages.length] = new WordImageRajah1();

		public static var RapunzelImages:Array = new Array();
		[Embed(source="../../media/words/rapunzel_1.jpg")]
		public static var WordImageRapunzel1:Class;
		RapunzelImages[RapunzelImages.length] = new WordImageRapunzel1();

		[Embed(source="../../media/words/rapunzel_2.jpg")]
		public static var WordImageRapunzel2:Class;
		RapunzelImages[RapunzelImages.length] = new WordImageRapunzel2();

		[Embed(source="../../media/words/rapunzel_3.jpg")]
		public static var WordImageRapunzel3:Class;
		RapunzelImages[RapunzelImages.length] = new WordImageRapunzel3();

		[Embed(source="../../media/words/rapunzel_4.jpg")]
		public static var WordImageRapunzel4:Class;
		RapunzelImages[RapunzelImages.length] = new WordImageRapunzel4();

		[Embed(source="../../media/words/rapunzel_5.jpg")]
		public static var WordImageRapunzel5:Class;
		RapunzelImages[RapunzelImages.length] = new WordImageRapunzel5();

		public static var RayImages:Array = new Array();
		[Embed(source="../../media/words/ray_1.jpg")]
		public static var WordImageRay1:Class;
		RayImages[RayImages.length] = new WordImageRay1();

		public static var ScarecrowImages:Array = new Array();
		[Embed(source="../../media/words/scarecrow_1.jpg")]
		public static var WordImageScarecrow1:Class;
		ScarecrowImages[ScarecrowImages.length] = new WordImageScarecrow1();

		public static var ScoobyDooImages:Array = new Array();
		[Embed(source="../../media/words/scooby-doo_1.jpg")]
		public static var WordImageScoobyDoo1:Class;
		ScoobyDooImages[ScoobyDooImages.length] = new WordImageScoobyDoo1();

		public static var ScuttleImages:Array = new Array();
		[Embed(source="../../media/words/scuttle_1.jpg")]
		public static var WordImageScuttle1:Class;
		ScuttleImages[ScuttleImages.length] = new WordImageScuttle1();

		[Embed(source="../../media/words/scuttle_2.gif")]
		public static var WordImageScuttle2:Class;
		ScuttleImages[ScuttleImages.length] = new WordImageScuttle2();

		[Embed(source="../../media/words/scuttle_3.jpg")]
		public static var WordImageScuttle3:Class;
		ScuttleImages[ScuttleImages.length] = new WordImageScuttle3();

		public static var SebastianImages:Array = new Array();
		[Embed(source="../../media/words/sebastian_1.gif")]
		public static var WordImageSebastian1:Class;
		SebastianImages[SebastianImages.length] = new WordImageSebastian1();

		[Embed(source="../../media/words/sebastian_2.gif")]
		public static var WordImageSebastian2:Class;
		SebastianImages[SebastianImages.length] = new WordImageSebastian2();

		[Embed(source="../../media/words/sebastian_3.jpg")]
		public static var WordImageSebastian3:Class;
		SebastianImages[SebastianImages.length] = new WordImageSebastian3();

		[Embed(source="../../media/words/sebastian_5.gif")]
		public static var WordImageSebastian5:Class;
		SebastianImages[SebastianImages.length] = new WordImageSebastian5();

		[Embed(source="../../media/words/sebastian_6.gif")]
		public static var WordImageSebastian6:Class;
		SebastianImages[SebastianImages.length] = new WordImageSebastian6();

		[Embed(source="../../media/words/sebastian_8.gif")]
		public static var WordImageSebastian8:Class;
		SebastianImages[SebastianImages.length] = new WordImageSebastian8();

		public static var SebatianImages:Array = new Array();
		[Embed(source="../../media/words/sebatian_7.jpg")]
		public static var WordImageSebatian7:Class;
		SebatianImages[SebatianImages.length] = new WordImageSebatian7();

		public static var ShaggyImages:Array = new Array();
		[Embed(source="../../media/words/shaggy_1.jpg")]
		public static var WordImageShaggy1:Class;
		ShaggyImages[ShaggyImages.length] = new WordImageShaggy1();

		public static var ShrekImages:Array = new Array();
		[Embed(source="../../media/words/shrek_1.jpg")]
		public static var WordImageShrek1:Class;
		ShrekImages[ShrekImages.length] = new WordImageShrek1();

		public static var SnowWhiteImages:Array = new Array();
		[Embed(source="../../media/words/snow-white_1.jpg")]
		public static var WordImageSnowWhite1:Class;
		SnowWhiteImages[SnowWhiteImages.length] = new WordImageSnowWhite1();

		public static var SultanImages:Array = new Array();
		[Embed(source="../../media/words/sultan_1.jpg")]
		public static var WordImageSultan1:Class;
		SultanImages[SultanImages.length] = new WordImageSultan1();

		public static var ThumperImages:Array = new Array();
		[Embed(source="../../media/words/thumper_1.jpg")]
		public static var WordImageThumper1:Class;
		ThumperImages[ThumperImages.length] = new WordImageThumper1();

		public static var TianaImages:Array = new Array();
		[Embed(source="../../media/words/tiana_1.jpg")]
		public static var WordImageTiana1:Class;
		TianaImages[TianaImages.length] = new WordImageTiana1();

		public static var TinManImages:Array = new Array();
		[Embed(source="../../media/words/tin-man_1.jpg")]
		public static var WordImageTinMan1:Class;
		TinManImages[TinManImages.length] = new WordImageTinMan1();

		public static var TinkerbellImages:Array = new Array();
		[Embed(source="../../media/words/tinkerbell_1.jpg")]
		public static var WordImageTinkerbell1:Class;
		TinkerbellImages[TinkerbellImages.length] = new WordImageTinkerbell1();

		[Embed(source="../../media/words/tinkerbell_2.gif")]
		public static var WordImageTinkerbell2:Class;
		TinkerbellImages[TinkerbellImages.length] = new WordImageTinkerbell2();

		[Embed(source="../../media/words/tinkerbell_3.jpg")]
		public static var WordImageTinkerbell3:Class;
		TinkerbellImages[TinkerbellImages.length] = new WordImageTinkerbell3();

		public static var TotoImages:Array = new Array();
		[Embed(source="../../media/words/toto_1.jpg")]
		public static var WordImageToto1:Class;
		TotoImages[TotoImages.length] = new WordImageToto1();

		[Embed(source="../../media/words/toto_2.jpg")]
		public static var WordImageToto2:Class;
		TotoImages[TotoImages.length] = new WordImageToto2();

		public static var UrsulaImages:Array = new Array();
		[Embed(source="../../media/words/ursula_1.gif")]
		public static var WordImageUrsula1:Class;
		UrsulaImages[UrsulaImages.length] = new WordImageUrsula1();

		[Embed(source="../../media/words/ursula_2.gif")]
		public static var WordImageUrsula2:Class;
		UrsulaImages[UrsulaImages.length] = new WordImageUrsula2();

		public static var VolcanoImages:Array = new Array();
		[Embed(source="../../media/words/volcano_1.jpg")]
		public static var WordImageVolcano1:Class;
		VolcanoImages[VolcanoImages.length] = new WordImageVolcano1();

		public static var WendyImages:Array = new Array();
		[Embed(source="../../media/words/wendy_1.jpg")]
		public static var WordImageWendy1:Class;
		WendyImages[WendyImages.length] = new WordImageWendy1();

		[Embed(source="../../media/words/wendy_2.gif")]
		public static var WordImageWendy2:Class;
		WendyImages[WendyImages.length] = new WordImageWendy2();

		public static var WinnieThePoohImages:Array = new Array();
		[Embed(source="../../media/words/winnie-the-pooh_1.jpg")]
		public static var WordImageWinnieThePooh1:Class;
		WinnieThePoohImages[WinnieThePoohImages.length] = new WordImageWinnieThePooh1();

		public static var WitchImages:Array = new Array();
		[Embed(source="../../media/words/witch_1.jpg")]
		public static var WordImageWitch1:Class;
		WitchImages[WitchImages.length] = new WordImageWitch1();

		[Embed(source="../../media/words/witch_2.jpg")]
		public static var WordImageWitch2:Class;
		WitchImages[WitchImages.length] = new WordImageWitch2();

		public static var WolfImages:Array = new Array();
		[Embed(source="../../media/words/wolf_1.jpg")]
		public static var WordImageWolf1:Class;
		WolfImages[WolfImages.length] = new WordImageWolf1();

		public static var WoodyImages:Array = new Array();
		[Embed(source="../../media/words/woody_1.jpg")]
		public static var WordImageWoody1:Class;
		WoodyImages[WoodyImages.length] = new WordImageWoody1();

		public static var XylophoneImages:Array = new Array();
		[Embed(source="../../media/words/xylophone_1.jpg")]
		public static var WordImageXylophone1:Class;
		XylophoneImages[XylophoneImages.length] = new WordImageXylophone1();

		public static var YetiImages:Array = new Array();
		[Embed(source="../../media/words/yeti_1.jpg")]
		public static var WordImageYeti1:Class;
		YetiImages[YetiImages.length] = new WordImageYeti1();

		[Embed(source="../../media/words/yeti_2.jpg")]
		public static var WordImageYeti2:Class;
		YetiImages[YetiImages.length] = new WordImageYeti2();

		public static var ZebraImages:Array = new Array();
		[Embed(source="../../media/words/zebra_1.gif")]
		public static var WordImageZebra1:Class;
		ZebraImages[ZebraImages.length] = new WordImageZebra1();

		[Embed(source="../../media/words/zebra_2.jpg")]
		public static var WordImageZebra2:Class;
		ZebraImages[ZebraImages.length] = new WordImageZebra2();

		public static var ZhuZhuPetImages:Array = new Array();
		[Embed(source="../../media/words/zhu-zhu-pet_1.jpg")]
		public static var WordImageZhuZhuPet1:Class;
		ZhuZhuPetImages[ZhuZhuPetImages.length] = new WordImageZhuZhuPet1();

		public function startup(canvas:Canvas):void
		{
			this.canvas = canvas;
			
			
			WordsByLetter["A"] = new Array();
			Words["ALADDIN"] = new Word("ALADDIN", "ALADDIN", AladdinImages);
			Words["ALADDIN"].startup(canvas);
			WordsByLetter["A"][WordsByLetter["A"].length] = Words["ALADDIN"];
			Words["ARIEL"] = new Word("ARIEL", "ARIEL", ArielImages);
			Words["ARIEL"].startup(canvas);
			WordsByLetter["A"][WordsByLetter["A"].length] = Words["ARIEL"];

			WordsByLetter["B"] = new Array();
			Words["BAMBI"] = new Word("BAMBI", "BAMBI", BambiImages);
			Words["BAMBI"].startup(canvas);
			WordsByLetter["B"][WordsByLetter["B"].length] = Words["BAMBI"];
			Words["BEAST"] = new Word("BEAST", "BEAST", BeastImages);
			Words["BEAST"].startup(canvas);
			WordsByLetter["B"][WordsByLetter["B"].length] = Words["BEAST"];
			Words["BELLE"] = new Word("BELLE", "BELLE", BelleImages);
			Words["BELLE"].startup(canvas);
			WordsByLetter["B"][WordsByLetter["B"].length] = Words["BELLE"];
			Words["BLOSSOM"] = new Word("BLOSSOM", "BLOSSOM", BlossomImages);
			Words["BLOSSOM"].startup(canvas);
			WordsByLetter["B"][WordsByLetter["B"].length] = Words["BLOSSOM"];
			Words["BUBBLES"] = new Word("BUBBLES", "BUBBLES", BubblesImages);
			Words["BUBBLES"].startup(canvas);
			WordsByLetter["B"][WordsByLetter["B"].length] = Words["BUBBLES"];
			Words["BUTTERCUP"] = new Word("BUTTERCUP", "BUTTERCUP", ButtercupImages);
			Words["BUTTERCUP"].startup(canvas);
			WordsByLetter["B"][WordsByLetter["B"].length] = Words["BUTTERCUP"];

			WordsByLetter["C"] = new Array();
			Words["CAT"] = new Word("CAT", "CAT", CatImages);
			Words["CAT"].startup(canvas);
			WordsByLetter["C"][WordsByLetter["C"].length] = Words["CAT"];
			Words["CHIP"] = new Word("CHIP", "CHIP", ChipImages);
			Words["CHIP"].startup(canvas);
			WordsByLetter["C"][WordsByLetter["C"].length] = Words["CHIP"];
			Words["CINDERELLA"] = new Word("CINDERELLA", "CINDERELLA", CinderellaImages);
			Words["CINDERELLA"].startup(canvas);
			WordsByLetter["C"][WordsByLetter["C"].length] = Words["CINDERELLA"];
			Words["COGSWORTH"] = new Word("COGSWORTH", "COGSWORTH", CogsworthImages);
			Words["COGSWORTH"].startup(canvas);
			WordsByLetter["C"][WordsByLetter["C"].length] = Words["COGSWORTH"];

			WordsByLetter["D"] = new Array();
			Words["DAISY"] = new Word("DAISY", "DAISY", DaisyImages);
			Words["DAISY"].startup(canvas);
			WordsByLetter["D"][WordsByLetter["D"].length] = Words["DAISY"];
			Words["DOG"] = new Word("DOG", "DOG", DogImages);
			Words["DOG"].startup(canvas);
			WordsByLetter["D"][WordsByLetter["D"].length] = Words["DOG"];
			Words["DONALD"] = new Word("DONALD", "DONALD", DonaldImages);
			Words["DONALD"].startup(canvas);
			WordsByLetter["D"][WordsByLetter["D"].length] = Words["DONALD"];
			Words["DONKEY"] = new Word("DONKEY", "DONKEY", DonkeyImages);
			Words["DONKEY"].startup(canvas);
			WordsByLetter["D"][WordsByLetter["D"].length] = Words["DONKEY"];
			Words["DOPEY"] = new Word("DOPEY", "DOPEY", DopeyImages);
			Words["DOPEY"].startup(canvas);
			WordsByLetter["D"][WordsByLetter["D"].length] = Words["DOPEY"];
			Words["DOROTHY"] = new Word("DOROTHY", "DOROTHY", DorothyImages);
			Words["DOROTHY"].startup(canvas);
			WordsByLetter["D"][WordsByLetter["D"].length] = Words["DOROTHY"];
			Words["DRAGON"] = new Word("DRAGON", "DRAGON", DragonImages);
			Words["DRAGON"].startup(canvas);
			WordsByLetter["D"][WordsByLetter["D"].length] = Words["DRAGON"];
			Words["DUMBO"] = new Word("DUMBO", "DUMBO", DumboImages);
			Words["DUMBO"].startup(canvas);
			WordsByLetter["D"][WordsByLetter["D"].length] = Words["DUMBO"];

			WordsByLetter["E"] = new Array();
			Words["EEYORE"] = new Word("EEYORE", "EEYORE", EeyoreImages);
			Words["EEYORE"].startup(canvas);
			WordsByLetter["E"][WordsByLetter["E"].length] = Words["EEYORE"];
			Words["EGG"] = new Word("EGG", "EGG", EggImages);
			Words["EGG"].startup(canvas);
			WordsByLetter["E"][WordsByLetter["E"].length] = Words["EGG"];
			Words["ERIC"] = new Word("ERIC", "ERIC", EricImages);
			Words["ERIC"].startup(canvas);
			WordsByLetter["E"][WordsByLetter["E"].length] = Words["ERIC"];

			WordsByLetter["F"] = new Array();
			Words["FAIRY"] = new Word("FAIRY", "FAIRY", FairyImages);
			Words["FAIRY"].startup(canvas);
			WordsByLetter["F"][WordsByLetter["F"].length] = Words["FAIRY"];
			Words["FIONA"] = new Word("FIONA", "FIONA", FionaImages);
			Words["FIONA"].startup(canvas);
			WordsByLetter["F"][WordsByLetter["F"].length] = Words["FIONA"];
			Words["FLOUNDER"] = new Word("FLOUNDER", "FLOUNDER", FlounderImages);
			Words["FLOUNDER"].startup(canvas);
			WordsByLetter["F"][WordsByLetter["F"].length] = Words["FLOUNDER"];
			Words["FLYNN_RIDER"] = new Word("FLYNN_RIDER", "FLYNN_RIDER", FlynnRiderImages);
			Words["FLYNN_RIDER"].startup(canvas);
			WordsByLetter["F"][WordsByLetter["F"].length] = Words["FLYNN_RIDER"];

			WordsByLetter["G"] = new Array();
			Words["GASTON"] = new Word("GASTON", "GASTON", GastonImages);
			Words["GASTON"].startup(canvas);
			WordsByLetter["G"][WordsByLetter["G"].length] = Words["GASTON"];
			Words["GENIE"] = new Word("GENIE", "GENIE", GenieImages);
			Words["GENIE"].startup(canvas);
			WordsByLetter["G"][WordsByLetter["G"].length] = Words["GENIE"];
			Words["GINGERBREAD_MAN"] = new Word("GINGERBREAD_MAN", "GINGERBREAD_MAN", GingerbreadManImages);
			Words["GINGERBREAD_MAN"].startup(canvas);
			WordsByLetter["G"][WordsByLetter["G"].length] = Words["GINGERBREAD_MAN"];
			Words["GOOFY"] = new Word("GOOFY", "GOOFY", GoofyImages);
			Words["GOOFY"].startup(canvas);
			WordsByLetter["G"][WordsByLetter["G"].length] = Words["GOOFY"];
			Words["GUS_GUS"] = new Word("GUS_GUS", "GUS_GUS", GusGusImages);
			Words["GUS_GUS"].startup(canvas);
			WordsByLetter["G"][WordsByLetter["G"].length] = Words["GUS_GUS"];

			WordsByLetter["H"] = new Array();
			Words["HAMSTER"] = new Word("HAMSTER", "HAMSTER", HamsterImages);
			Words["HAMSTER"].startup(canvas);
			WordsByLetter["H"][WordsByLetter["H"].length] = Words["HAMSTER"];
			Words["HANNAH_MONTANA"] = new Word("HANNAH_MONTANA", "HANNAH_MONTANA", HannahMontanaImages);
			Words["HANNAH_MONTANA"].startup(canvas);
			WordsByLetter["H"][WordsByLetter["H"].length] = Words["HANNAH_MONTANA"];
			Words["HIPPO"] = new Word("HIPPO", "HIPPO", HippoImages);
			Words["HIPPO"].startup(canvas);
			WordsByLetter["H"][WordsByLetter["H"].length] = Words["HIPPO"];

			WordsByLetter["I"] = new Array();
			Words["IAGO"] = new Word("IAGO", "IAGO", IagoImages);
			Words["IAGO"].startup(canvas);
			WordsByLetter["I"][WordsByLetter["I"].length] = Words["IAGO"];
			Words["ICE_CREAM"] = new Word("ICE_CREAM", "ICE_CREAM", IceCreamImages);
			Words["ICE_CREAM"].startup(canvas);
			WordsByLetter["I"][WordsByLetter["I"].length] = Words["ICE_CREAM"];

			WordsByLetter["J"] = new Array();
			Words["JAQ"] = new Word("JAQ", "JAQ", JaqImages);
			Words["JAQ"].startup(canvas);
			WordsByLetter["J"][WordsByLetter["J"].length] = Words["JAQ"];
			Words["JASMINE"] = new Word("JASMINE", "JASMINE", JasmineImages);
			Words["JASMINE"].startup(canvas);
			WordsByLetter["J"][WordsByLetter["J"].length] = Words["JASMINE"];
			Words["JESSIE"] = new Word("JESSIE", "JESSIE", JessieImages);
			Words["JESSIE"].startup(canvas);
			WordsByLetter["J"][WordsByLetter["J"].length] = Words["JESSIE"];
			Words["JIMINY_CRICKET"] = new Word("JIMINY_CRICKET", "JIMINY_CRICKET", JiminyCricketImages);
			Words["JIMINY_CRICKET"].startup(canvas);
			WordsByLetter["J"][WordsByLetter["J"].length] = Words["JIMINY_CRICKET"];

			WordsByLetter["K"] = new Array();
			Words["KING_TRITON"] = new Word("KING_TRITON", "KING_TRITON", KingTritonImages);
			Words["KING_TRITON"].startup(canvas);
			WordsByLetter["K"][WordsByLetter["K"].length] = Words["KING_TRITON"];
			Words["KITTEN"] = new Word("KITTEN", "KITTEN", KittenImages);
			Words["KITTEN"].startup(canvas);
			WordsByLetter["K"][WordsByLetter["K"].length] = Words["KITTEN"];

			WordsByLetter["L"] = new Array();
			Words["LION"] = new Word("LION", "LION", LionImages);
			Words["LION"].startup(canvas);
			WordsByLetter["L"][WordsByLetter["L"].length] = Words["LION"];
			Words["LOUIS"] = new Word("LOUIS", "LOUIS", LouisImages);
			Words["LOUIS"].startup(canvas);
			WordsByLetter["L"][WordsByLetter["L"].length] = Words["LOUIS"];
			Words["LUMIERE"] = new Word("LUMIERE", "LUMIERE", LumiereImages);
			Words["LUMIERE"].startup(canvas);
			WordsByLetter["L"][WordsByLetter["L"].length] = Words["LUMIERE"];

			WordsByLetter["M"] = new Array();
			Words["MALEFICENT"] = new Word("MALEFICENT", "MALEFICENT", MaleficentImages);
			Words["MALEFICENT"].startup(canvas);
			WordsByLetter["M"][WordsByLetter["M"].length] = Words["MALEFICENT"];
			Words["MICKEY"] = new Word("MICKEY", "MICKEY", MickeyImages);
			Words["MICKEY"].startup(canvas);
			WordsByLetter["M"][WordsByLetter["M"].length] = Words["MICKEY"];
			Words["MINNIE"] = new Word("MINNIE", "MINNIE", MinnieImages);
			Words["MINNIE"].startup(canvas);
			WordsByLetter["M"][WordsByLetter["M"].length] = Words["MINNIE"];
			Words["MOJO_JOJO"] = new Word("MOJO_JOJO", "MOJO_JOJO", MojoJojoImages);
			Words["MOJO_JOJO"].startup(canvas);
			WordsByLetter["M"][WordsByLetter["M"].length] = Words["MOJO_JOJO"];

			WordsByLetter["N"] = new Array();
			Words["NAVEEN"] = new Word("NAVEEN", "NAVEEN", NaveenImages);
			Words["NAVEEN"].startup(canvas);
			WordsByLetter["N"][WordsByLetter["N"].length] = Words["NAVEEN"];

			WordsByLetter["O"] = new Array();
			Words["OWL"] = new Word("OWL", "OWL", OwlImages);
			Words["OWL"].startup(canvas);
			WordsByLetter["O"][WordsByLetter["O"].length] = Words["OWL"];

			WordsByLetter["P"] = new Array();
			Words["PASCAL"] = new Word("PASCAL", "PASCAL", PascalImages);
			Words["PASCAL"].startup(canvas);
			WordsByLetter["P"][WordsByLetter["P"].length] = Words["PASCAL"];
			Words["PINOCCHIO"] = new Word("PINOCCHIO", "PINOCCHIO", PinocchioImages);
			Words["PINOCCHIO"].startup(canvas);
			WordsByLetter["P"][WordsByLetter["P"].length] = Words["PINOCCHIO"];
			Words["PLUTO"] = new Word("PLUTO", "PLUTO", PlutoImages);
			Words["PLUTO"].startup(canvas);
			WordsByLetter["P"][WordsByLetter["P"].length] = Words["PLUTO"];
			Words["POWERPUFF_GIRLS"] = new Word("POWERPUFF_GIRLS", "POWERPUFF_GIRLS", PowerpuffGirlsImages);
			Words["POWERPUFF_GIRLS"].startup(canvas);
			WordsByLetter["P"][WordsByLetter["P"].length] = Words["POWERPUFF_GIRLS"];
			Words["PRINCE"] = new Word("PRINCE", "PRINCE", PrinceImages);
			Words["PRINCE"].startup(canvas);
			WordsByLetter["P"][WordsByLetter["P"].length] = Words["PRINCE"];
			Words["PUSS_IN_BOOTS"] = new Word("PUSS_IN_BOOTS", "PUSS_IN_BOOTS", PussInBootsImages);
			Words["PUSS_IN_BOOTS"].startup(canvas);
			WordsByLetter["P"][WordsByLetter["P"].length] = Words["PUSS_IN_BOOTS"];

			WordsByLetter["Q"] = new Array();
			Words["QUEEN"] = new Word("QUEEN", "QUEEN", QueenImages);
			Words["QUEEN"].startup(canvas);
			WordsByLetter["Q"][WordsByLetter["Q"].length] = Words["QUEEN"];

			WordsByLetter["R"] = new Array();
			Words["RAJAH"] = new Word("RAJAH", "RAJAH", RajahImages);
			Words["RAJAH"].startup(canvas);
			WordsByLetter["R"][WordsByLetter["R"].length] = Words["RAJAH"];
			Words["RAPUNZEL"] = new Word("RAPUNZEL", "RAPUNZEL", RapunzelImages);
			Words["RAPUNZEL"].startup(canvas);
			WordsByLetter["R"][WordsByLetter["R"].length] = Words["RAPUNZEL"];
			Words["RAY"] = new Word("RAY", "RAY", RayImages);
			Words["RAY"].startup(canvas);
			WordsByLetter["R"][WordsByLetter["R"].length] = Words["RAY"];

			WordsByLetter["S"] = new Array();
			Words["SCARECROW"] = new Word("SCARECROW", "SCARECROW", ScarecrowImages);
			Words["SCARECROW"].startup(canvas);
			WordsByLetter["S"][WordsByLetter["S"].length] = Words["SCARECROW"];
			Words["SCOOBY_DOO"] = new Word("SCOOBY_DOO", "SCOOBY_DOO", ScoobyDooImages);
			Words["SCOOBY_DOO"].startup(canvas);
			WordsByLetter["S"][WordsByLetter["S"].length] = Words["SCOOBY_DOO"];
			Words["SCUTTLE"] = new Word("SCUTTLE", "SCUTTLE", ScuttleImages);
			Words["SCUTTLE"].startup(canvas);
			WordsByLetter["S"][WordsByLetter["S"].length] = Words["SCUTTLE"];
			Words["SEBASTIAN"] = new Word("SEBASTIAN", "SEBASTIAN", SebastianImages);
			Words["SEBASTIAN"].startup(canvas);
			WordsByLetter["S"][WordsByLetter["S"].length] = Words["SEBASTIAN"];
			Words["SEBATIAN"] = new Word("SEBATIAN", "SEBATIAN", SebatianImages);
			Words["SEBATIAN"].startup(canvas);
			WordsByLetter["S"][WordsByLetter["S"].length] = Words["SEBATIAN"];
			Words["SHAGGY"] = new Word("SHAGGY", "SHAGGY", ShaggyImages);
			Words["SHAGGY"].startup(canvas);
			WordsByLetter["S"][WordsByLetter["S"].length] = Words["SHAGGY"];
			Words["SHREK"] = new Word("SHREK", "SHREK", ShrekImages);
			Words["SHREK"].startup(canvas);
			WordsByLetter["S"][WordsByLetter["S"].length] = Words["SHREK"];
			Words["SNOW_WHITE"] = new Word("SNOW_WHITE", "SNOW_WHITE", SnowWhiteImages);
			Words["SNOW_WHITE"].startup(canvas);
			WordsByLetter["S"][WordsByLetter["S"].length] = Words["SNOW_WHITE"];
			Words["SULTAN"] = new Word("SULTAN", "SULTAN", SultanImages);
			Words["SULTAN"].startup(canvas);
			WordsByLetter["S"][WordsByLetter["S"].length] = Words["SULTAN"];

			WordsByLetter["T"] = new Array();
			Words["THUMPER"] = new Word("THUMPER", "THUMPER", ThumperImages);
			Words["THUMPER"].startup(canvas);
			WordsByLetter["T"][WordsByLetter["T"].length] = Words["THUMPER"];
			Words["TIANA"] = new Word("TIANA", "TIANA", TianaImages);
			Words["TIANA"].startup(canvas);
			WordsByLetter["T"][WordsByLetter["T"].length] = Words["TIANA"];
			Words["TIN_MAN"] = new Word("TIN_MAN", "TIN_MAN", TinManImages);
			Words["TIN_MAN"].startup(canvas);
			WordsByLetter["T"][WordsByLetter["T"].length] = Words["TIN_MAN"];
			Words["TINKERBELL"] = new Word("TINKERBELL", "TINKERBELL", TinkerbellImages);
			Words["TINKERBELL"].startup(canvas);
			WordsByLetter["T"][WordsByLetter["T"].length] = Words["TINKERBELL"];
			Words["TOTO"] = new Word("TOTO", "TOTO", TotoImages);
			Words["TOTO"].startup(canvas);
			WordsByLetter["T"][WordsByLetter["T"].length] = Words["TOTO"];

			WordsByLetter["U"] = new Array();
			Words["URSULA"] = new Word("URSULA", "URSULA", UrsulaImages);
			Words["URSULA"].startup(canvas);
			WordsByLetter["U"][WordsByLetter["U"].length] = Words["URSULA"];

			WordsByLetter["V"] = new Array();
			Words["VOLCANO"] = new Word("VOLCANO", "VOLCANO", VolcanoImages);
			Words["VOLCANO"].startup(canvas);
			WordsByLetter["V"][WordsByLetter["V"].length] = Words["VOLCANO"];

			WordsByLetter["W"] = new Array();
			Words["WENDY"] = new Word("WENDY", "WENDY", WendyImages);
			Words["WENDY"].startup(canvas);
			WordsByLetter["W"][WordsByLetter["W"].length] = Words["WENDY"];
			Words["WINNIE_THE_POOH"] = new Word("WINNIE_THE_POOH", "WINNIE_THE_POOH", WinnieThePoohImages);
			Words["WINNIE_THE_POOH"].startup(canvas);
			WordsByLetter["W"][WordsByLetter["W"].length] = Words["WINNIE_THE_POOH"];
			Words["WITCH"] = new Word("WITCH", "WITCH", WitchImages);
			Words["WITCH"].startup(canvas);
			WordsByLetter["W"][WordsByLetter["W"].length] = Words["WITCH"];
			Words["WOLF"] = new Word("WOLF", "WOLF", WolfImages);
			Words["WOLF"].startup(canvas);
			WordsByLetter["W"][WordsByLetter["W"].length] = Words["WOLF"];
			Words["WOODY"] = new Word("WOODY", "WOODY", WoodyImages);
			Words["WOODY"].startup(canvas);
			WordsByLetter["W"][WordsByLetter["W"].length] = Words["WOODY"];

			WordsByLetter["X"] = new Array();
			Words["XYLOPHONE"] = new Word("XYLOPHONE", "XYLOPHONE", XylophoneImages);
			Words["XYLOPHONE"].startup(canvas);
			WordsByLetter["X"][WordsByLetter["X"].length] = Words["XYLOPHONE"];

			WordsByLetter["Y"] = new Array();
			Words["YETI"] = new Word("YETI", "YETI", YetiImages);
			Words["YETI"].startup(canvas);
			WordsByLetter["Y"][WordsByLetter["Y"].length] = Words["YETI"];

			WordsByLetter["Z"] = new Array();
			Words["ZEBRA"] = new Word("ZEBRA", "ZEBRA", ZebraImages);
			Words["ZEBRA"].startup(canvas);
			WordsByLetter["Z"][WordsByLetter["Z"].length] = Words["ZEBRA"];
			Words["ZHU_ZHU_PET"] = new Word("ZHU_ZHU_PET", "ZHU_ZHU_PET", ZhuZhuPetImages);
			Words["ZHU_ZHU_PET"].startup(canvas);
			WordsByLetter["Z"][WordsByLetter["Z"].length] = Words["ZHU_ZHU_PET"];

		}

	}
}
